version: "3.7"

services:
    # app
    app-superlogica-test:
        container_name: app-superlogica-test
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel-network

    # nginx
    nginx:
        container_name: superlogica-nginx
        image: nginx:alpine
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-network

    # mysql
    mysql:
        container_name: superlogica-mysql
        image: mysql:5.7.22
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - laravel-network

    # phpmyadmin
    phpmyadmin:
        container_name: superlogica-phpmyadmin
        image: phpmyadmin:5.1.3
        environment:
            PMA_HOST: superlogica-mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 8080:80
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge
